	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_unknown_taiko::
	.incbin "sound/direct_sound_samples/unknown_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
Cry_CSanae::
	.incbin "sound/direct_sound_samples/cry_csanae.bin"

	.align 2
Cry_Sanae::
	.incbin "sound/direct_sound_samples/cry_sanae.bin"

	.align 2
Cry_CAlice::
	.incbin "sound/direct_sound_samples/cry_calice.bin"

	.align 2
Cry_Alice::
	.incbin "sound/direct_sound_samples/cry_alice.bin"

	.align 2
Cry_CReisen::
	.incbin "sound/direct_sound_samples/cry_creisen.bin"

	.align 2
Cry_Reisen::
	.incbin "sound/direct_sound_samples/cry_reisen.bin"

	.align 2
Cry_CLilyWhite::
	.incbin "sound/direct_sound_samples/cry_clilywhite.bin"

	.align 2
Cry_LilyWhite::
	.incbin "sound/direct_sound_samples/cry_lilywhite.bin"

	.align 2
Cry_CLilyBlack::
	.incbin "sound/direct_sound_samples/cry_clilyblack.bin"

	.align 2
Cry_LilyBlack::
	.incbin "sound/direct_sound_samples/cry_lilyblack.bin"

	.align 2
Cry_CMomiji::
	.incbin "sound/direct_sound_samples/cry_cmomiji.bin"

	.align 2
Cry_Momiji::
	.incbin "sound/direct_sound_samples/cry_momiji.bin"

	.align 2
Cry_CShizuha::
	.incbin "sound/direct_sound_samples/cry_cshizuha.bin"

	.align 2
Cry_Shizuha::
	.incbin "sound/direct_sound_samples/cry_shizuha.bin"

	.align 2
Cry_CMedicine::
	.incbin "sound/direct_sound_samples/cry_cmedicine.bin"

	.align 2
Cry_Medicine::
	.incbin "sound/direct_sound_samples/cry_medicine.bin"

	.align 2
Cry_CKoakuma::
	.incbin "sound/direct_sound_samples/cry_ckoakuma.bin"

	.align 2
Cry_Koakuma::
	.incbin "sound/direct_sound_samples/cry_koakuma.bin"

	.align 2
Cry_CNazrin::
	.incbin "sound/direct_sound_samples/cry_cnazrin.bin"

	.align 2
Cry_Nazrin::
	.incbin "sound/direct_sound_samples/cry_nazrin.bin"

	.align 2
Cry_CTokiko::
	.incbin "sound/direct_sound_samples/cry_ctokiko.bin"

	.align 2
Cry_Tokiko::
	.incbin "sound/direct_sound_samples/cry_tokiko.bin"

	.align 2
Cry_CRemilia::
	.incbin "sound/direct_sound_samples/cry_cremilia.bin"

	.align 2
Cry_Remilia::
	.incbin "sound/direct_sound_samples/cry_remilia.bin"

	.align 2
Cry_CCirno::
	.incbin "sound/direct_sound_samples/cry_ccirno.bin"

	.align 2
Cry_Cirno::
	.incbin "sound/direct_sound_samples/cry_cirno.bin"

	.align 2
Cry_CRumia::
	.incbin "sound/direct_sound_samples/cry_crumia.bin"

	.align 2
Cry_Rumia::
	.incbin "sound/direct_sound_samples/cry_rumia.bin"

	.align 2
Cry_Shanghai::
	.incbin "sound/direct_sound_samples/cry_shanghai.bin"

	.align 2
Cry_CFlandre::
	.incbin "sound/direct_sound_samples/cry_cflandre.bin"

	.align 2
Cry_Flandre::
	.incbin "sound/direct_sound_samples/cry_flandre.bin"

	.align 2
Cry_Hourai::
	.incbin "sound/direct_sound_samples/cry_hourai.bin"

	.align 2
Cry_CYoumu::
	.incbin "sound/direct_sound_samples/cry_cyoumu.bin"

	.align 2
Cry_Youmu::
	.incbin "sound/direct_sound_samples/cry_youmu.bin"

	.align 2
Cry_CYukari::
	.incbin "sound/direct_sound_samples/cry_cyukari.bin"

	.align 2
Cry_Yukari::
	.incbin "sound/direct_sound_samples/cry_yukari.bin"

	.align 2
Cry_CSuika::
	.incbin "sound/direct_sound_samples/cry_csuika.bin"

	.align 2
Cry_Suika::
	.incbin "sound/direct_sound_samples/cry_suika.bin"

	.align 2
Cry_CMystia::
	.incbin "sound/direct_sound_samples/cry_cmystia.bin"

	.align 2
Cry_Mystia::
	.incbin "sound/direct_sound_samples/cry_mystia.bin"

	.align 2
Cry_CMinoriko::
	.incbin "sound/direct_sound_samples/cry_cminoriko.bin"

	.align 2
Cry_Minoriko::
	.incbin "sound/direct_sound_samples/cry_minoriko.bin"

	.align 2
Cry_CKeine::
	.incbin "sound/direct_sound_samples/cry_ckeine.bin"

	.align 2
Cry_Keine::
	.incbin "sound/direct_sound_samples/cry_keine.bin"

	.align 2
Cry_AKeine::
	.incbin "sound/direct_sound_samples/cry_akeine.bin"

	.align 2
Cry_CIku::
	.incbin "sound/direct_sound_samples/cry_ciku.bin"

	.align 2
Cry_Iku::
	.incbin "sound/direct_sound_samples/cry_iku.bin"

	.align 2
Cry_CKoishi::
	.incbin "sound/direct_sound_samples/cry_ckoishi.bin"

	.align 2
Cry_Koishi::
	.incbin "sound/direct_sound_samples/cry_koishi.bin"

	.align 2
Cry_CYamame::
	.incbin "sound/direct_sound_samples/cry_cyamame.bin"

	.align 2
Cry_Yamame::
	.incbin "sound/direct_sound_samples/cry_yamame.bin"

	.align 2
Cry_CChen::
	.incbin "sound/direct_sound_samples/cry_cchen.bin"

	.align 2
Cry_Chen::
	.incbin "sound/direct_sound_samples/cry_chen.bin"

	.align 2
Cry_CYorihime::
	.incbin "sound/direct_sound_samples/cry_cyorihime.bin"

	.align 2
Cry_Yorihime::
	.incbin "sound/direct_sound_samples/cry_yorihime.bin"

	.align 2
Cry_CKaguya::
	.incbin "sound/direct_sound_samples/cry_ckaguya.bin"

	.align 2
Cry_Kaguya::
	.incbin "sound/direct_sound_samples/cry_kaguya.bin"

	.align 2
Cry_CMokou::
	.incbin "sound/direct_sound_samples/cry_cmokou.bin"

	.align 2
Cry_Mokou::
	.incbin "sound/direct_sound_samples/cry_mokou.bin"

	.align 2
Cry_CHatate::
	.incbin "sound/direct_sound_samples/cry_chatate.bin"

	.align 2
Cry_Hatate::
	.incbin "sound/direct_sound_samples/cry_hatate.bin"

	.align 2
Cry_CLetty::
	.incbin "sound/direct_sound_samples/cry_cletty.bin"

	.align 2
Cry_Letty::
	.incbin "sound/direct_sound_samples/cry_letty.bin"

	.align 2
Cry_CPatchouli::
	.incbin "sound/direct_sound_samples/cry_cpatchouli.bin"

	.align 2
Cry_Patchouli::
	.incbin "sound/direct_sound_samples/cry_patchouli.bin"

	.align 2
Cry_CYuugi::
	.incbin "sound/direct_sound_samples/cry_cyuugi.bin"

	.align 2
Cry_Yuugi::
	.incbin "sound/direct_sound_samples/cry_yuugi.bin"

	.align 2
Cry_CTenshi::
	.incbin "sound/direct_sound_samples/cry_ctenshi.bin"

	.align 2
Cry_Tenshi::
	.incbin "sound/direct_sound_samples/cry_tenshi.bin"

	.align 2
Cry_CParsee::
	.incbin "sound/direct_sound_samples/cry_cparsee.bin"

	.align 2
Cry_Parsee::
	.incbin "sound/direct_sound_samples/cry_parsee.bin"

	.align 2
Cry_CMurasa::
	.incbin "sound/direct_sound_samples/cry_cmurasa.bin"

	.align 2
Cry_Murasa::
	.incbin "sound/direct_sound_samples/cry_murasa.bin"

	.align 2
Cry_CKisume::
	.incbin "sound/direct_sound_samples/cry_ckisume.bin"

	.align 2
Cry_Kisume::
	.incbin "sound/direct_sound_samples/cry_kisume.bin"

	.align 2
Cry_CKogasa::
	.incbin "sound/direct_sound_samples/cry_ckogasa.bin"

	.align 2
Cry_Kogasa::
	.incbin "sound/direct_sound_samples/cry_kogasa.bin"

	.align 2
Cry_CSatori::
	.incbin "sound/direct_sound_samples/cry_csatori.bin"

	.align 2
Cry_Satori::
	.incbin "sound/direct_sound_samples/cry_satori.bin"

	.align 2
Cry_CEirin::
	.incbin "sound/direct_sound_samples/cry_ceirin.bin"

	.align 2
Cry_Eirin::
	.incbin "sound/direct_sound_samples/cry_eirin.bin"

	.align 2
Cry_CRan::
	.incbin "sound/direct_sound_samples/cry_cran.bin"

	.align 2
Cry_Ran::
	.incbin "sound/direct_sound_samples/cry_ran.bin"

	.align 2
Cry_CDaiyousei::
	.incbin "sound/direct_sound_samples/cry_cdaiyousei.bin"

	.align 2
Cry_Daiyousei::
	.incbin "sound/direct_sound_samples/cry_daiyousei.bin"

	.align 2
Cry_CNitori::
	.incbin "sound/direct_sound_samples/cry_cnitori.bin"

	.align 2
Cry_Nitori::
	.incbin "sound/direct_sound_samples/cry_nitori.bin"

	.align 2
Cry_CHina::
	.incbin "sound/direct_sound_samples/cry_china.bin"

	.align 2
Cry_Hina::
	.incbin "sound/direct_sound_samples/cry_hina.bin"

	.align 2
Cry_CKomachi::
	.incbin "sound/direct_sound_samples/cry_ckomachi.bin"

	.align 2
Cry_Komachi::
	.incbin "sound/direct_sound_samples/cry_komachi.bin"

	.align 2
Cry_CYuyuko::
	.incbin "sound/direct_sound_samples/cry_cyuyuko.bin"

	.align 2
Cry_Yuyuko::
	.incbin "sound/direct_sound_samples/cry_yuyuko.bin"

	.align 2
Cry_CMeiling::
	.incbin "sound/direct_sound_samples/cry_cmeiling.bin"

	.align 2
Cry_Meiling::
	.incbin "sound/direct_sound_samples/cry_meiling.bin"

	.align 2
Cry_CSakuya::
	.incbin "sound/direct_sound_samples/cry_csakuya.bin"

	.align 2
Cry_Sakuya::
	.incbin "sound/direct_sound_samples/cry_sakuya.bin"

	.align 2
Cry_CLunasa::
	.incbin "sound/direct_sound_samples/cry_clunasa.bin"

	.align 2
Cry_Lunasa::
	.incbin "sound/direct_sound_samples/cry_lunasa.bin"

	.align 2
Cry_CMerlin::
	.incbin "sound/direct_sound_samples/cry_cmerlin.bin"

	.align 2
Cry_Merlin::
	.incbin "sound/direct_sound_samples/cry_merlin.bin"

	.align 2
Cry_CLyrica::
	.incbin "sound/direct_sound_samples/cry_clyrica.bin"

	.align 2
Cry_Lyrica::
	.incbin "sound/direct_sound_samples/cry_lyrica.bin"

	.align 2
Cry_CLayla::
	.incbin "sound/direct_sound_samples/cry_clayla.bin"

	.align 2
Cry_Layla::
	.incbin "sound/direct_sound_samples/cry_layla.bin"

	.align 2
Cry_CKanako::
	.incbin "sound/direct_sound_samples/cry_ckanako.bin"

	.align 2
Cry_Kanako::
	.incbin "sound/direct_sound_samples/cry_kanako.bin"

	.align 2
Cry_CRin::
	.incbin "sound/direct_sound_samples/cry_crin.bin"

	.align 2
Cry_Rin::
	.incbin "sound/direct_sound_samples/cry_rin.bin"

	.align 2
Cry_CUtsuho::
	.incbin "sound/direct_sound_samples/cry_cutsuho.bin"

	.align 2
Cry_Utsuho::
	.incbin "sound/direct_sound_samples/cry_utsuho.bin"

	.align 2
Cry_CIchirin::
	.incbin "sound/direct_sound_samples/cry_cichirin.bin"

	.align 2
Cry_Ichirin::
	.incbin "sound/direct_sound_samples/cry_ichirin.bin"

	.align 2
Cry_CSunnyMilk::
	.incbin "sound/direct_sound_samples/cry_csunnymilk.bin"

	.align 2
Cry_SunnyMilk::
	.incbin "sound/direct_sound_samples/cry_sunnymilk.bin"

	.align 2
Cry_CLunaChild::
	.incbin "sound/direct_sound_samples/cry_clunachild.bin"

	.align 2
Cry_LunaChild::
	.incbin "sound/direct_sound_samples/cry_lunachild.bin"

	.align 2
Cry_CStarSapphire::
	.incbin "sound/direct_sound_samples/cry_cstarsapphire.bin"

	.align 2
Cry_StarSapphire::
	.incbin "sound/direct_sound_samples/cry_starsapphire.bin"

	.align 2
Cry_CYuuka::
	.incbin "sound/direct_sound_samples/cry_cyuuka.bin"

	.align 2
Cry_Yuuka::
	.incbin "sound/direct_sound_samples/cry_yuuka.bin"

	.align 2
Cry_CAya::
	.incbin "sound/direct_sound_samples/cry_caya.bin"

	.align 2
Cry_Aya::
	.incbin "sound/direct_sound_samples/cry_aya.bin"

	.align 2
Cry_CShikieiki::
	.incbin "sound/direct_sound_samples/cry_cshikieiki.bin"

	.align 2
Cry_Shikieiki::
	.incbin "sound/direct_sound_samples/cry_shikieiki.bin"

	.align 2
Cry_CShou::
	.incbin "sound/direct_sound_samples/cry_cshou.bin"

	.align 2
Cry_Shou::
	.incbin "sound/direct_sound_samples/cry_shou.bin"

	.align 2
Cry_CWriggle::
	.incbin "sound/direct_sound_samples/cry_cwriggle.bin"

	.align 2
Cry_Wriggle::
	.incbin "sound/direct_sound_samples/cry_wriggle.bin"

	.align 2
Cry_CTewi::
	.incbin "sound/direct_sound_samples/cry_ctewi.bin"

	.align 2
Cry_Tewi::
	.incbin "sound/direct_sound_samples/cry_tewi.bin"

	.align 2
Cry_Kedama::
	.incbin "sound/direct_sound_samples/cry_kedama.bin"

	.align 2
Cry_CNue::
	.incbin "sound/direct_sound_samples/cry_cnue.bin"

	.align 2
Cry_Nue::
	.incbin "sound/direct_sound_samples/cry_nue.bin"

	.align 2
Cry_CSuwako::
	.incbin "sound/direct_sound_samples/cry_csuwako.bin"

	.align 2
Cry_Suwako::
	.incbin "sound/direct_sound_samples/cry_suwako.bin"

	.align 2
Cry_Reysen::
	.incbin "sound/direct_sound_samples/cry_reysen.bin"

	.align 2
Cry_CMarisa::
	.incbin "sound/direct_sound_samples/cry_cmarisa.bin"

	.align 2
Cry_Marisa::
	.incbin "sound/direct_sound_samples/cry_marisa.bin"

	.align 2
Cry_CReimu::
	.incbin "sound/direct_sound_samples/cry_creimu.bin"

	.align 2
Cry_Reimu::
	.incbin "sound/direct_sound_samples/cry_reimu.bin"

	.align 2
Cry_CByakuren::
	.incbin "sound/direct_sound_samples/cry_cbyakuren.bin"

	.align 2
Cry_Byakuren::
	.incbin "sound/direct_sound_samples/cry_byakuren.bin"

	.align 2
Cry_Konngara::
	.incbin "sound/direct_sound_samples/cry_konngara.bin"

	.align 2
Cry_Kikuri::
	.incbin "sound/direct_sound_samples/cry_kikuri.bin"

	.align 2
Cry_YuugenMagan::
	.incbin "sound/direct_sound_samples/cry_yuugenmagan.bin"

	.align 2
Cry_CToyohime::
	.incbin "sound/direct_sound_samples/cry_ctoyohime.bin"

	.align 2
Cry_Toyohime::
	.incbin "sound/direct_sound_samples/cry_toyohime.bin"

	.align 2
Cry_Goliath::
	.incbin "sound/direct_sound_samples/cry_goliath.bin"

	.align 2
Cry_Sariel::
	.incbin "sound/direct_sound_samples/cry_sariel.bin"

	.align 2
Cry_Akyuu::
	.incbin "sound/direct_sound_samples/cry_akyuu.bin"

	.align 2
Cry_Genji::
	.incbin "sound/direct_sound_samples/cry_genji.bin"

	.align 2
Cry_Tori::
	.incbin "sound/direct_sound_samples/cry_tori.bin"

	.align 2
Cry_Namazu::
	.incbin "sound/direct_sound_samples/cry_namazu.bin"

	.align 2
Cry_CElly::
	.incbin "sound/direct_sound_samples/cry_celly.bin"

	.align 2
Cry_Elly::
	.incbin "sound/direct_sound_samples/cry_elly.bin"

	.align 2
Cry_COrange::
	.incbin "sound/direct_sound_samples/cry_corange.bin"

	.align 2
Cry_Orange::
	.incbin "sound/direct_sound_samples/cry_orange.bin"

	.align 2
Cry_Youki::
	.incbin "sound/direct_sound_samples/cry_youki.bin"

	.align 2
Cry_CChiyuri::
	.incbin "sound/direct_sound_samples/cry_cchiyuri.bin"

	.align 2
Cry_Chiyuri::
	.incbin "sound/direct_sound_samples/cry_chiyuri.bin"

	.align 2
Cry_CYumemi::
	.incbin "sound/direct_sound_samples/cry_cyumemi.bin"

	.align 2
Cry_Yumemi::
	.incbin "sound/direct_sound_samples/cry_yumemi.bin"

	.align 2
Cry_CEllen::
	.incbin "sound/direct_sound_samples/cry_cellen.bin"

	.align 2
Cry_Ellen::
	.incbin "sound/direct_sound_samples/cry_ellen.bin"

	.align 2
Cry_CKazami::
	.incbin "sound/direct_sound_samples/cry_ckazami.bin"

	.align 2
Cry_Kazami::
	.incbin "sound/direct_sound_samples/cry_kazami.bin"

	.align 2
Cry_CMeira::
	.incbin "sound/direct_sound_samples/cry_cmeira.bin"

	.align 2
Cry_Meira::
	.incbin "sound/direct_sound_samples/cry_meira.bin"

	.align 2
Cry_CSara::
	.incbin "sound/direct_sound_samples/cry_csara.bin"

	.align 2
Cry_Sara::
	.incbin "sound/direct_sound_samples/cry_sara.bin"

	.align 2
Cry_CLuize::
	.incbin "sound/direct_sound_samples/cry_cluize.bin"

	.align 2
Cry_Luize::
	.incbin "sound/direct_sound_samples/cry_luize.bin"

	.align 2
Cry_CMargatroid::
	.incbin "sound/direct_sound_samples/cry_cmargatroid.bin"

	.align 2
Cry_Margatroid::
	.incbin "sound/direct_sound_samples/cry_margatroid.bin"

	.align 2
Cry_CKana::
	.incbin "sound/direct_sound_samples/cry_ckana.bin"

	.align 2
Cry_Kana::
	.incbin "sound/direct_sound_samples/cry_kana.bin"

	.align 2
Cry_CHakurei::
	.incbin "sound/direct_sound_samples/cry_chakurei.bin"

	.align 2
Cry_Hakurei::
	.incbin "sound/direct_sound_samples/cry_hakurei.bin"

	.align 2
Cry_CKirisame::
	.incbin "sound/direct_sound_samples/cry_ckirisame.bin"

	.align 2
Cry_Kirisame::
	.incbin "sound/direct_sound_samples/cry_kirisame.bin"

	.align 2
Cry_CKotohime::
	.incbin "sound/direct_sound_samples/cry_ckotohime.bin"

	.align 2
Cry_Kotohime::
	.incbin "sound/direct_sound_samples/cry_kotohime.bin"

	.align 2
Cry_CYumeko::
	.incbin "sound/direct_sound_samples/cry_cyumeko.bin"

	.align 2
Cry_Yumeko::
	.incbin "sound/direct_sound_samples/cry_yumeko.bin"

	.align 2
Cry_CShinki::
	.incbin "sound/direct_sound_samples/cry_cshinki.bin"

	.align 2
Cry_Shinki::
	.incbin "sound/direct_sound_samples/cry_shinki.bin"

	.align 2
Cry_Mimi::
	.incbin "sound/direct_sound_samples/cry_mimi.bin"

	.align 2
Cry_Ruukoto::
	.incbin "sound/direct_sound_samples/cry_ruukoto.bin"

	.align 2
Cry_CRika::
	.incbin "sound/direct_sound_samples/cry_crika.bin"

	.align 2
Cry_Rika::
	.incbin "sound/direct_sound_samples/cry_rika.bin"

	.align 2
Cry_CMugetsu::
	.incbin "sound/direct_sound_samples/cry_cmugetsu.bin"

	.align 2
Cry_Mugetsu::
	.incbin "sound/direct_sound_samples/cry_mugetsu.bin"

	.align 2
Cry_CGengetsu::
	.incbin "sound/direct_sound_samples/cry_cgengetsu.bin"

	.align 2
Cry_Gengetsu::
	.incbin "sound/direct_sound_samples/cry_gengetsu.bin"

	.align 2
Cry_CKurumi::
	.incbin "sound/direct_sound_samples/cry_ckurumi.bin"

	.align 2
Cry_Kurumi::
	.incbin "sound/direct_sound_samples/cry_kurumi.bin"

	.align 2
Cry_CRikako::
	.incbin "sound/direct_sound_samples/cry_crikako.bin"

	.align 2
Cry_Rikako::
	.incbin "sound/direct_sound_samples/cry_rikako.bin"

	.align 2
Cry_CYuki::
	.incbin "sound/direct_sound_samples/cry_cyuki.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cry_unown.bin"

	.align 2
Cry_CMai::
	.incbin "sound/direct_sound_samples/cry_cmai.bin"

	.align 2
Cry_Mai::
	.incbin "sound/direct_sound_samples/cry_mai.bin"

	.align 2
Cry_DSunnyMilk::
	.incbin "sound/direct_sound_samples/cry_dsunnymilk.bin"

	.align 2
Cry_TLunaChild::
	.incbin "sound/direct_sound_samples/cry_tlunachild.bin"

	.align 2
Cry_HStarSapphire::
	.incbin "sound/direct_sound_samples/cry_hstarsapphire.bin"

	.align 2
Cry_ANitori::
	.incbin "sound/direct_sound_samples/cry_anitori.bin"

	.align 2
Cry_TNitori::
	.incbin "sound/direct_sound_samples/cry_tnitori.bin"

	.align 2
Cry_AMokou::
	.incbin "sound/direct_sound_samples/cry_amokou.bin"

	.align 2
Cry_DMokou::
	.incbin "sound/direct_sound_samples/cry_dmokou.bin"

	.align 2
Cry_DReisen::
	.incbin "sound/direct_sound_samples/cry_dreisen.bin"

	.align 2
Cry_TReisen::
	.incbin "sound/direct_sound_samples/cry_treisen.bin"

	.align 2
Cry_TSakuya::
	.incbin "sound/direct_sound_samples/cry_tsakuya.bin"

	.align 2
Cry_HSakuya::
	.incbin "sound/direct_sound_samples/cry_hsakuya.bin"

	.align 2
Cry_ARumia::
	.incbin "sound/direct_sound_samples/cry_arumia.bin"

	.align 2
Cry_SRumia::
	.incbin "sound/direct_sound_samples/cry_srumia.bin"

	.align 2
Cry_HMystia::
	.incbin "sound/direct_sound_samples/cry_hmystia.bin"

	.align 2
Cry_AMystia::
	.incbin "sound/direct_sound_samples/cry_amystia.bin"

	.align 2
Cry_AChen::
	.incbin "sound/direct_sound_samples/cry_achen.bin"

	.align 2
Cry_TChen::
	.incbin "sound/direct_sound_samples/cry_tchen.bin"

	.align 2
Cry_DYoumu::
	.incbin "sound/direct_sound_samples/cry_dyoumu.bin"

	.align 2
Cry_SYoumu::
	.incbin "sound/direct_sound_samples/cry_syoumu.bin"

	.align 2
Cry_AYuuka::
	.incbin "sound/direct_sound_samples/cry_ayuuka.bin"

	.align 2
Cry_TYuuka::
	.incbin "sound/direct_sound_samples/cry_tyuuka.bin"

	.align 2
Cry_SAya::
	.incbin "sound/direct_sound_samples/cry_saya.bin"

	.align 2
Cry_TAya::
	.incbin "sound/direct_sound_samples/cry_taya.bin"

	.align 2
Cry_ATenshi::
	.incbin "sound/direct_sound_samples/cry_atenshi.bin"

	.align 2
Cry_DTenshi::
	.incbin "sound/direct_sound_samples/cry_dtenshi.bin"

	.align 2
Cry_DParsee::
	.incbin "sound/direct_sound_samples/cry_dparsee.bin"

	.align 2
Cry_TParsee::
	.incbin "sound/direct_sound_samples/cry_tparsee.bin"

	.align 2
Cry_AKoishi::
	.incbin "sound/direct_sound_samples/cry_akoishi.bin"

	.align 2
Cry_SKoishi::
	.incbin "sound/direct_sound_samples/cry_skoishi.bin"

	.align 2
Cry_DByakuren::
	.incbin "sound/direct_sound_samples/cry_dbyakuren.bin"

	.align 2
Cry_TByakuren::
	.incbin "sound/direct_sound_samples/cry_tbyakuren.bin"

	.align 2
Cry_DIchirin::
	.incbin "sound/direct_sound_samples/cry_dichirin.bin"

	.align 2
Cry_TIchirin::
	.incbin "sound/direct_sound_samples/cry_tichirin.bin"

	.align 2
Cry_AKanako::
	.incbin "sound/direct_sound_samples/cry_akanako.bin"

	.align 2
Cry_DKanako::
	.incbin "sound/direct_sound_samples/cry_dkanako.bin"

	.align 2
Cry_AKaguya::
	.incbin "sound/direct_sound_samples/cry_akaguya.bin"

	.align 2
Cry_DKaguya::
	.incbin "sound/direct_sound_samples/cry_dkaguya.bin"

	.align 2
Cry_ShinGyokuO::
	.incbin "sound/direct_sound_samples/cry_shingyokuo.bin"

	.align 2
Cry_ShinGyokuM::
	.incbin "sound/direct_sound_samples/cry_shingyokum.bin"

	.align 2
Cry_ShinGyokuF::
	.incbin "sound/direct_sound_samples/cry_shingyokuf.bin"

	.align 2
Cry_AUtsuho::
	.incbin "sound/direct_sound_samples/cry_autsuho.bin"

	.align 2
Cry_SUtsuho::
	.incbin "sound/direct_sound_samples/cry_sutsuho.bin"

	.align 2
Cry_DMomiji::
	.incbin "sound/direct_sound_samples/cry_dmomiji.bin"

	.align 2
Cry_Elis::
	.incbin "sound/direct_sound_samples/cry_elis.bin"

	.align 2
Cry_Mima::
	.incbin "sound/direct_sound_samples/cry_mima.bin"

	.align 2
Cry_SKomachi::
	.incbin "sound/direct_sound_samples/cry_skomachi.bin"

	.align 2
Cry_AKomachi::
	.incbin "sound/direct_sound_samples/cry_akomachi.bin"

	.align 2
Cry_AEirin::
	.incbin "sound/direct_sound_samples/cry_aeirin.bin"

	.align 2
Cry_SWriggle::
	.incbin "sound/direct_sound_samples/cry_swriggle.bin"

	.align 2
Cry_AdvReisen::
	.incbin "sound/direct_sound_samples/cry_advreisen.bin"

	.align 2
Cry_CSariel::
	.incbin "sound/direct_sound_samples/cry_csariel.bin"

	.align 2
Cry_AShikieiki::
	.incbin "sound/direct_sound_samples/cry_ashikieiki.bin"

	.align 2
Cry_TToyohime::
	.incbin "sound/direct_sound_samples/cry_ttoyohime.bin"

	.align 2
Cry_Rinnosuke::
	.incbin "sound/direct_sound_samples/cry_rinnosuke.bin"

	.align 2
Cry_Mamizou::
	.incbin "sound/direct_sound_samples/cry_mamizou.bin"

	.align 2
Cry_AMinoriko::
	.incbin "sound/direct_sound_samples/cry_aminoriko.bin"

	.align 2
Cry_TSatori::
	.incbin "sound/direct_sound_samples/cry_tsatori.bin"

	.align 2
Cry_DShikieiki::
	.incbin "sound/direct_sound_samples/cry_dshikieiki.bin"

	.align 2
Cry_DSatori::
	.incbin "sound/direct_sound_samples/cry_dsatori.bin"

	.align 2
Cry_CShinGyoku::
	.incbin "sound/direct_sound_samples/cry_cshingyoku.bin"

	.align 2
Cry_DIku::
	.incbin "sound/direct_sound_samples/cry_diku.bin"

	.align 2
Cry_TIku::
	.incbin "sound/direct_sound_samples/cry_tiku.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cry_unused_265.bin"

	.align 2
Cry_TShou::
	.incbin "sound/direct_sound_samples/cry_tshou.bin"

	.align 2
Cry_ATokiko::
	.incbin "sound/direct_sound_samples/cry_atokiko.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cry_unused_268.bin"

	.align 2
Cry_SKogasa::
	.incbin "sound/direct_sound_samples/cry_skogasa.bin"

	.align 2
Cry_AAlice::
	.incbin "sound/direct_sound_samples/cry_aalice.bin"

	.align 2
Cry_TAlice::
	.incbin "sound/direct_sound_samples/cry_talice.bin"

	.align 2
Cry_AReimu::
	.incbin "sound/direct_sound_samples/cry_areimu.bin"

	.align 2
Cry_HEirin::
	.incbin "sound/direct_sound_samples/cry_heirin.bin"

	.align 2
Cry_DYukari::
	.incbin "sound/direct_sound_samples/cry_dyukari.bin"

	.align 2
Cry_TYukari::
	.incbin "sound/direct_sound_samples/cry_tyukari.bin"

	.align 2
Cry_DReimu::
	.incbin "sound/direct_sound_samples/cry_dreimu.bin"

	.align 2
Cry_SCirno::
	.incbin "sound/direct_sound_samples/cry_scirno.bin"

	.align 2
Cry_TCirno::
	.incbin "sound/direct_sound_samples/cry_tcirno.bin"

	.align 2
Cry_DRemilia::
	.incbin "sound/direct_sound_samples/cry_dremilia.bin"

	.align 2
Cry_TKogasa::
	.incbin "sound/direct_sound_samples/cry_tkogasa.bin"

	.align 2
Cry_TYamame::
	.incbin "sound/direct_sound_samples/cry_tyamame.bin"

	.align 2
Cry_DDaiyousei::
	.incbin "sound/direct_sound_samples/cry_ddaiyousei.bin"

	.align 2
Cry_AHina::
	.incbin "sound/direct_sound_samples/cry_ahina.bin"

	.align 2
Cry_DHina::
	.incbin "sound/direct_sound_samples/cry_dhina.bin"

	.align 2
Cry_SShizuha::
	.incbin "sound/direct_sound_samples/cry_sshizuha.bin"

	.align 2
Cry_SRin::
	.incbin "sound/direct_sound_samples/cry_srin.bin"

	.align 2
Cry_ARin::
	.incbin "sound/direct_sound_samples/cry_arin.bin"

	.align 2
Cry_ZombieFairy::
	.incbin "sound/direct_sound_samples/cry_zombiefairy.bin"

	.align 2
Cry_ATewi::
	.incbin "sound/direct_sound_samples/cry_atewi.bin"

	.align 2
Cry_HLyrica::
	.incbin "sound/direct_sound_samples/cry_hlyrica.bin"

	.align 2
Cry_ARan::
	.incbin "sound/direct_sound_samples/cry_aran.bin"

	.align 2
Cry_HRan::
	.incbin "sound/direct_sound_samples/cry_hran.bin"

	.align 2
Cry_AMedicine::
	.incbin "sound/direct_sound_samples/cry_amedicine.bin"

	.align 2
Cry_TMedicine::
	.incbin "sound/direct_sound_samples/cry_tmedicine.bin"

	.align 2
Cry_Tenma::
	.incbin "sound/direct_sound_samples/cry_tenma.bin"

	.align 2
Cry_Sendai::
	.incbin "sound/direct_sound_samples/cry_sendai.bin"

	.align 2
Cry_CKyouko::
	.incbin "sound/direct_sound_samples/cry_ckyouko.bin"

	.align 2
Cry_SSariel::
	.incbin "sound/direct_sound_samples/cry_ssariel.bin"

	.align 2
Cry_ALilyWhite::
	.incbin "sound/direct_sound_samples/cry_alilywhite.bin"

	.align 2
Cry_CMima::
	.incbin "sound/direct_sound_samples/cry_cmima.bin"

	.align 2
Cry_HShizuha::
	.incbin "sound/direct_sound_samples/cry_hshizuha.bin"

	.align 2
Cry_ASuwako::
	.incbin "sound/direct_sound_samples/cry_asuwako.bin"

	.align 2
Cry_AShou::
	.incbin "sound/direct_sound_samples/cry_ashou.bin"

	.align 2
Cry_AFlandre::
	.incbin "sound/direct_sound_samples/cry_aflandre.bin"

	.align 2
Cry_ADaiyousei::
	.incbin "sound/direct_sound_samples/cry_adaiyousei.bin"

	.align 2
Cry_CElis::
	.incbin "sound/direct_sound_samples/cry_celis.bin"

	.align 2
Cry_DLetty::
	.incbin "sound/direct_sound_samples/cry_dletty.bin"

	.align 2
Cry_TNazrin::
	.incbin "sound/direct_sound_samples/cry_tnazrin.bin"

	.align 2
Cry_HNazrin::
	.incbin "sound/direct_sound_samples/cry_hnazrin.bin"

	.align 2
Cry_SFlandre::
	.incbin "sound/direct_sound_samples/cry_sflandre.bin"

	.align 2
Cry_DWriggle::
	.incbin "sound/direct_sound_samples/cry_dwriggle.bin"

	.align 2
Cry_ASunnyMilk::
	.incbin "sound/direct_sound_samples/cry_asunnymilk.bin"

	.align 2
Cry_ALunaChild::
	.incbin "sound/direct_sound_samples/cry_alunachild.bin"

	.align 2
Cry_CKikuri::
	.incbin "sound/direct_sound_samples/cry_ckikuri.bin"

	.align 2
Cry_AdvMeiling::
	.incbin "sound/direct_sound_samples/cry_advmeiling.bin"

	.align 2
Cry_CKonngara::
	.incbin "sound/direct_sound_samples/cry_ckonngara.bin"

	.align 2
Cry_Magan::
	.incbin "sound/direct_sound_samples/cry_magan.bin"

	.align 2
Cry_THatate::
	.incbin "sound/direct_sound_samples/cry_thatate.bin"

	.align 2
Cry_DHatate::
	.incbin "sound/direct_sound_samples/cry_dhatate.bin"

	.align 2
Cry_DLayla::
	.incbin "sound/direct_sound_samples/cry_dlayla.bin"

	.align 2
Cry_DKeine::
	.incbin "sound/direct_sound_samples/cry_dkeine.bin"

	.align 2
Cry_ALilyBlack::
	.incbin "sound/direct_sound_samples/cry_alilyblack.bin"

	.align 2
Cry_DYuugi::
	.incbin "sound/direct_sound_samples/cry_dyuugi.bin"

	.align 2
Cry_DMinoriko::
	.incbin "sound/direct_sound_samples/cry_dminoriko.bin"

	.align 2
Cry_TSuika::
	.incbin "sound/direct_sound_samples/cry_tsuika.bin"

	.align 2
Cry_ASanae::
	.incbin "sound/direct_sound_samples/cry_asanae.bin"

	.align 2
Cry_ANue::
	.incbin "sound/direct_sound_samples/cry_anue.bin"

	.align 2
Cry_TNue::
	.incbin "sound/direct_sound_samples/cry_tnue.bin"

	.align 2
Cry_HKoakuma::
	.incbin "sound/direct_sound_samples/cry_hkoakuma.bin"

	.align 2
Cry_SMeiling::
	.incbin "sound/direct_sound_samples/cry_smeiling.bin"

	.align 2
Cry_HLetty::
	.incbin "sound/direct_sound_samples/cry_hletty.bin"

	.align 2
Cry_SYorihime::
	.incbin "sound/direct_sound_samples/cry_syorihime.bin"

	.align 2
Cry_ARemilia::
	.incbin "sound/direct_sound_samples/cry_aremilia.bin"

	.align 2
Cry_DTewi::
	.incbin "sound/direct_sound_samples/cry_dtewi.bin"

	.align 2
Cry_SMedicine::
	.incbin "sound/direct_sound_samples/cry_smedicine.bin"

	.align 2
Cry_AYuugi::
	.incbin "sound/direct_sound_samples/cry_ayuugi.bin"

	.align 2
Cry_HKeine::
	.incbin "sound/direct_sound_samples/cry_hkeine.bin"

	.align 2
Cry_ASuika::
	.incbin "sound/direct_sound_samples/cry_asuika.bin"

	.align 2
Cry_HLilyWhite::
	.incbin "sound/direct_sound_samples/cry_hlilywhite.bin"

	.align 2
Cry_SLilyBlack::
	.incbin "sound/direct_sound_samples/cry_slilyblack.bin"

	.align 2
Cry_AMurasa::
	.incbin "sound/direct_sound_samples/cry_amurasa.bin"

	.align 2
Cry_AStarSapphire::
	.incbin "sound/direct_sound_samples/cry_astarsapphire.bin"

	.align 2
Cry_AKazami::
	.incbin "sound/direct_sound_samples/cry_akazami.bin"

	.align 2
Cry_AdvYukari::
	.incbin "sound/direct_sound_samples/cry_advyukari.bin"

	.align 2
Cry_AdvRan::
	.incbin "sound/direct_sound_samples/cry_advran.bin"

	.align 2
Cry_AdvChen::
	.incbin "sound/direct_sound_samples/cry_advchen.bin"

	.align 2
Cry_DarkAlice::
	.incbin "sound/direct_sound_samples/cry_darkalice.bin"

	.align 2
Cry_CSeiga::
	.incbin "sound/direct_sound_samples/cry_cseiga.bin"

	.align 2
Cry_Seiga::
	.incbin "sound/direct_sound_samples/cry_seiga.bin"

	.align 2
Cry_CTojiko::
	.incbin "sound/direct_sound_samples/cry_ctojiko.bin"

	.align 2
Cry_Kyouko::
	.incbin "sound/direct_sound_samples/cry_kyouko.bin"

	.align 2
Cry_CYoshika::
	.incbin "sound/direct_sound_samples/cry_cyoshika.bin"

	.align 2
Cry_Tojiko::
	.incbin "sound/direct_sound_samples/cry_tojiko.bin"

	.align 2
Cry_CFuto::
	.incbin "sound/direct_sound_samples/cry_cfuto.bin"

	.align 2
Cry_Futo::
	.incbin "sound/direct_sound_samples/cry_futo.bin"

	.align 2
Cry_TSanae::
	.incbin "sound/direct_sound_samples/cry_tsanae.bin"

	.align 2
Cry_Yuki::
	.incbin "sound/direct_sound_samples/cry_yuki.bin"

	.align 2
Cry_AdvMokou::
	.incbin "sound/direct_sound_samples/cry_advmokou.bin"

	.align 2
Cry_DYuyuko::
	.incbin "sound/direct_sound_samples/cry_dyuyuko.bin"

	.align 2
Cry_AYuyuko::
	.incbin "sound/direct_sound_samples/cry_ayuyuko.bin"

	.align 2
Cry_AdvCirno::
	.incbin "sound/direct_sound_samples/cry_advcirno.bin"

	.align 2
Cry_AdvMystia::
	.incbin "sound/direct_sound_samples/cry_advmystia.bin"

	.align 2
Cry_TKisume::
	.incbin "sound/direct_sound_samples/cry_tkisume.bin"

	.align 2
Cry_AdvTewi::
	.incbin "sound/direct_sound_samples/cry_advtewi.bin"

	.align 2
Cry_AdvMarisa::
	.incbin "sound/direct_sound_samples/cry_advmarisa.bin"

	.align 2
Cry_AdvAlice::
	.incbin "sound/direct_sound_samples/cry_advalice.bin"

	.align 2
Cry_AdvLetty::
	.incbin "sound/direct_sound_samples/cry_advletty.bin"

	.align 2
Cry_AkiSisters::
	.incbin "sound/direct_sound_samples/cry_akisisters.bin"

	.align 2
Cry_Miko::
	.incbin "sound/direct_sound_samples/cry_miko.bin"

	.align 2
Cry_CMiko::
	.incbin "sound/direct_sound_samples/cry_cmiko.bin"

	.align 2
Cry_CMamizou::
	.incbin "sound/direct_sound_samples/cry_cmamizou.bin"

	.align 2
Cry_Yoshika::
	.incbin "sound/direct_sound_samples/cry_yoshika.bin"

	.align 2
Cry_SYamame::
	.incbin "sound/direct_sound_samples/cry_syamame.bin"

	.align 2
Cry_DSuwako::
	.incbin "sound/direct_sound_samples/cry_dsuwako.bin"

	.align 2
Cry_HMerlin::
	.incbin "sound/direct_sound_samples/cry_hmerlin.bin"

	.align 2
Cry_APatchouli::
	.incbin "sound/direct_sound_samples/cry_apatchouli.bin"

	.align 2
Cry_DMeiling::
	.incbin "sound/direct_sound_samples/cry_dmeiling.bin"

	.align 2
Cry_HLunasa::
	.incbin "sound/direct_sound_samples/cry_hlunasa.bin"

	.align 2
Cry_DMurasa::
	.incbin "sound/direct_sound_samples/cry_dmurasa.bin"

	.align 2
Cry_AMarisa::
	.incbin "sound/direct_sound_samples/cry_amarisa.bin"

	.align 2
Cry_Tensoku::
	.incbin "sound/direct_sound_samples/cry_tensoku.bin"

	.align 2
Cry_SMarisa::
	.incbin "sound/direct_sound_samples/cry_smarisa.bin"

	.align 2
Cry_DPatchouli::
	.incbin "sound/direct_sound_samples/cry_dpatchouli.bin"

	.align 2
Cry_CKasen::
	.incbin "sound/direct_sound_samples/cry_ckasen.bin"

	.align 2
Cry_Kasen::
	.incbin "sound/direct_sound_samples/cry_kasen.bin"

	.align 2
Cry_Gomaseki::
	.incbin "sound/direct_sound_samples/cry_gomaseki.bin"

	.align 2
Cry_CWakasagi::
	.incbin "sound/direct_sound_samples/cry_cwakasagi.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
